from abc import ABC, abstractmethod


class BaseLLMProvider(ABC):
    @abstractmethod
    def ask(self, document: str, question: str) -> str:
        """Return an answer generated by the LLM."""
        pass